"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username \
$directory\
$git_branch\
$git_status\
$dotnet\
"""

add_newline = false
[line_break]
disabled = false

[username]
show_always = true
style_user = 'red'

[directory]
style = "green"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"code" = "󰲋 "

[character]
success_symbol = "[❯](bold purple)"
error_symbol = "[✗](bold red) "

[git_branch]
symbol = " "

[git_status]

[dotnet]
