"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$git_status\
$dotnet\
$rust\
$gradle\
$java
"""

add_newline = false
[line_break]
disabled = true

[username]
show_always = true

[directory]

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Code" = "󰲋 "

[git_branch]
symbol = " "

[git_status]

[dotnet]
[rust]
[gradle]
[java]
